"""add index to production

Revision ID: d3c71c4b71bf
Revises: 44c9515dcf02
Create Date: 2026-02-25 11:19:27.811195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c71c4b71bf'
down_revision: Union[str, Sequence[str], None] = '44c9515dcf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_machine_timestamp', 'production_records', ['machine_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_machine_timestamp', table_name='production_records')
    # ### end Alembic commands ###
